### PR TITLE
Add `start` and `stop` instance methods to NSTimer

### PR DESCRIPTION
**Pull request by jayrhynas**
`start` is a convenience method to schedule an NSTimer on a NSRunLoop.
`stop` simply calls `invalidate` and is provided to mirror `start`.

### CODE REVIEW

**Comment by radex** [comment]
Thanks for the pull request. I like this. It certainly seems to make more sense for the API user to call `.start()` on a timer rather than use some shady `NSRunLoop` internals.

I made a few tweaks here: https://github.com/radex/SwiftyTimer/commit/2927287eba171893a201613d98646373a77e40b6

I have two worries/doubts:

1. `start` seems a bit weird to use when you want to schedule the timer for multiple run loop modes:
   
   ```swift
timer.start(mode: NSDefaultRunLoopMode)
timer.start(mode: NSEventTrackingRunLoopMode)
   ```

    It's as if you were starting the timer _twice_, not adding the same timer to two different run loop modes. Not sure what to think about this.

2. I like how `stop` sounds. But it's troubling, because as far as I can tell, `invalidate()` does more than just stop the timer — it literally stops is from ever firing again. (Or am I stupid and doing something wrong?)

**Comment by jayrhynas** [comment]
Those are some good points. It would probably make sense to pass multiple modes to `start` if needed.
So, you would call it like this:
  
    timer.start(modes: [NSDefaultRunLoopMode, NSEventTrackingRunLoopMode])

And you're right about `invalidate` - it doesn't look like there's a way to remove a timer from a run loop without invalidating it so it's probably better to just not provide the `stop` method.

**Comment by jayrhynas** [comment]
Another way to implement start could be:

    public func start(runLoop: NSRunLoop = NSRunLoop.currentRunLoop(), #modes: String...) {
        var modes = modes
        if modes.count == 0 {
          modes = [NSDefaultRunLoopMode]
        }

        for mode in modes {
            println("runLoop.addTimer(self, forMode: \(mode))")
        }
    }

So you can just call it like:

    timer.start(modes: NSDefaultRunLoopMode, NSEventTrackingRunLoopMode)

**Comment by radex** [comment]
I like that.

**Comment by jayrhynas** [comment]
I've updated the PR

**Comment by radex** [comment]
Awesome, thank you!

**Pull request merged**
