### PR TITLE
Swift 4.2 Migration

### PR DESCRIPTION
**Pull request by asowers1**
What this does:
- Updated for Swift 4.2 source compatibility
- Updated project file to reflect that
- Project test passing
- Travis test passing

### CODE REVIEW

**Comment by radex** [comment]
LGTM @asowers1! Thanks for the PR. Would you mind adding a changelog entry?

PS. I don't really maintain this repo anymore — I can give you GitHub and CocoaPods access if you want to take over

**Comment by asowers1** [comment]
Sounds good to me! I can take care of that.

**Comment by asowers1** [comment]
@radex, the changelog is set. I can move ahead with the new tag and pod repo update whenever you're ready.

**Comment by radex** [comment]
@asowers1 Added you as GitHub collaborator and given you access to CocoaPods. Go ahead with pushing the changes. Feel free to update the readme to give yourself credit as the maintainer ;)

**Pull request merged**
