### PR TITLE
add timer into closure

### PR DESCRIPTION
**Pull request by phamquochoan**
So people can call invalidate() inside closure

### CODE REVIEW

**Comment by radex** [comment]
But it you do that, then you'll *have to* write { timer in ... } when defining a closure, no?

**Comment by phamquochoan** [comment]
Yes, we will have to write that, or { _ in ... }
It's mainly for the sake of `NSTimer.every(#time#) { ... }` because most of the time we don't have to create a `var` or `let` for it.
We can write invalidate condition inside the closure.

With `NSTimer.after...`, we can keep the old way.

**Comment by radex** [comment]
Maybe we can overload every with a second variant that doesn't take any arguments in its closure? Can you check if it's possible to make the timer argument optional in some way?

**Comment by phamquochoan** [comment]
Theorically, yes. But I'm afraid of the error `ambiguous use of ...`
For example (this one from ExSwift):
`each (call: (Element) -> ())`
`each (call: (Int, Element) -> ())`

Sometimes I cannot use it likes `each { item in ... } ` or `each { $0.doSth() }`
I have to write it this way: `each { (index, item) in ... } or `each { (_, item) in ... } ` 
Swift thinks these methods are ambiguous, I don't know why though.

I'll give it a try.

**Comment by radex** [comment]
Thanks, hopefully Swift can handle this case :)

**Comment by phamquochoan** [comment]
`ambiguous use of 'after'`...

Best I can do is:

```swift
NSTimer.after(5.0.seconds) { // it works
       log("abc")
}
        
NSTimer.after(5.0.seconds) { (timer: NSTimer!) -> Void in // this one works too
        log("abc")
}

NSTimer.after(5.0.seconds) { timer in // ambiguous
        log("abc")
}
```

I have to doubled every function in souce code file, and it looks ugly because Objective-C doesn't handle function overload as well as swift.

**Comment by radex** [comment]
Done on master.

**Pull request closed without merging**
